---
language: node_js
node_js:
- '0.11'
- '0.10'
addons:
  firefox: "25.0"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
    - npm run test
branches:
    only:
        - master
        - develop
        - /^feature.*$/
        - /^hotfix.*$/
